# Generated by Selenium IDE
import time

import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait


@pytest.mark.testSuite
@pytest.mark.order
class TestOrderStatus():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_orderStatus(self):
        # Test name: OrderStatus
        # Step # | name | target | value
        # 1 | open | http://34.118.122.203/administration/index.php?controller=AdminLogin&token=1e53b83c6f3b96a3ca75976d5bab155e |
        self.driver.get("http://34.118.122.203/administration/index.php?controller=AdminLogin&token=1e53b83c6f3b96a3ca75976d5bab155e")
        # 2 | setWindowSize | 1936x1056 |
        self.driver.set_window_size(1936, 1056)
        # 3 | click | id=email |
        self.driver.find_element(By.ID, "email").click()
        # 4 | type | id=email | user@example.com
        self.driver.find_element(By.ID, "email").send_keys("user@example.com")
        # 5 | click | id=passwd |
        self.driver.find_element(By.ID, "passwd").click()
        # 6 | type | id=passwd | VTR6WmtBCvnZ
        self.driver.find_element(By.ID, "passwd").send_keys("VTR6WmtBCvnZ")
        # 7 | click | css=.ladda-label |
        self.driver.find_element(By.CSS_SELECTOR, ".ladda-label").click()
        WebDriverWait(self.driver, 10).until(lambda s: s.find_element(By.CSS_SELECTOR, "#subtab-AdminParentOrders > .link"))
        # 8 | click | css=#subtab-AdminParentOrders > .link |
        self.driver.find_element(By.CSS_SELECTOR, "#subtab-AdminParentOrders > .link").click()
        # 9 | click | linkText=Orders |
        self.driver.find_element(By.LINK_TEXT, "Orders").click()
        # 10 | click | id=order_reference |
        self.driver.find_element(By.ID, "order_reference").click()
        self.driver.find_element(By.ID, "order_reference").clear()
        # 11 | type | id=order_reference | KVIZLDDCT
        self.driver.find_element(By.ID, "order_reference").send_keys("KVIZLDDCT")
        # 12 | click | name=order[actions][search] |
        self.driver.find_element(By.NAME, "order[actions][search]").click()
        # 13 | click | css=.btn-secondary |
        self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary").click()
        # 14 | click | css=.js-dropdown-item:nth-child(9) |
        order_status = self.driver.find_element(By.XPATH, '//*[@id="order_grid_table"]//button[9]').text
        self.driver.find_element(By.CSS_SELECTOR, ".js-dropdown-item:nth-child(9)").click()
        # 15 | click | css=#header_shopname > span |
        self.vars["window_handles"] = self.driver.window_handles
        # 16 | selectWindow | handle=${win7818} |
        self.driver.find_element(By.CSS_SELECTOR, "#header_shopname > span").click()
        # 17 | click | css=a > .hidden-sm-down |
        self.vars["win7818"] = self.wait_for_window(2000)
        # 18 | click | id=field-email |
        self.driver.switch_to.window(self.vars["win7818"])
        # 19 | type | id=field-email | user@example.com
        self.driver.find_element(By.CSS_SELECTOR, "a > .hidden-sm-down").click()
        # 20 | click | id=field-password |
        self.driver.find_element(By.ID, "field-email").click()
        # 21 | type | id=field-password | 123456789
        self.driver.find_element(By.ID, "field-email").send_keys("user@example.com")
        # 22 | click | id=submit-login |
        self.driver.find_element(By.ID, "field-password").click()
        # 23 | click | css=#history-link > .link-item |
        self.driver.find_element(By.ID, "field-password").send_keys("123456789")
        # 24 | click | css=#subtab-AdminParentOrders > .link |
        self.driver.find_element(By.ID, "submit-login").click()
        # 25 | click | linkText=Orders |
        self.driver.find_element(By.CSS_SELECTOR, "#history-link > .link-item").click()
        assert order_status in self.driver.find_element(By.ID, 'content').text
        self.driver.get("http://34.118.122.203/administration/index.php?controller=AdminLogin&token=1e53b83c6f3b96a3ca75976d5bab155e")
        # 26 | click | id=order_reference |
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("user@example.com")
        self.driver.find_element(By.ID, "passwd").click()
        self.driver.find_element(By.ID, "passwd").send_keys("VTR6WmtBCvnZ")
        self.driver.find_element(By.CSS_SELECTOR, ".ladda-label").click()
        WebDriverWait(self.driver, 10).until(lambda s: s.find_element(By.CSS_SELECTOR, "#subtab-AdminParentOrders > .link"))
        self.driver.find_element(By.CSS_SELECTOR, "#subtab-AdminParentOrders > .link").click()
        # 27 | click | name=order[actions][search] |
        self.driver.find_element(By.LINK_TEXT, "Orders").click()
        # 28 | click | css=.btn-secondary |
        self.driver.find_element(By.ID, "order_reference").click()
        # 29 | click | css=.js-dropdown-item:nth-child(9) |
        self.driver.find_element(By.NAME, "order[actions][search]").click()
        # 30 | click | css=#header_shopname > span |
        self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary").click()
        # 31 | selectWindow | handle=${win2750} |
        order_status = self.driver.find_element(By.XPATH, '//*[@id="order_grid_table"]//button[9]').text
        self.driver.find_element(By.CSS_SELECTOR, ".js-dropdown-item:nth-child(9)").click()
        # 32 | click | css=.account > .hidden-sm-down |
        self.vars["window_handles"] = self.driver.window_handles
        # 33 | click | css=#history-link .material-icons |
        self.driver.find_element(By.CSS_SELECTOR, "#header_shopname > span").click()
        self.vars["win2750"] = self.wait_for_window(2000)
        self.driver.switch_to.window(self.vars["win2750"])
        WebDriverWait(self.driver, 10).until(lambda s: s.find_element(By.XPATH, '//*[@id="_desktop_user_info"]/div/a[2]'))
        self.driver.find_element(By.XPATH, '//*[@id="_desktop_user_info"]/div/a[2]').click()
        WebDriverWait(self.driver, 10).until(lambda s: s.find_element(By.CSS_SELECTOR, "#history-link .material-icons"))
        self.driver.find_element(By.CSS_SELECTOR, "#history-link .material-icons").click()
        assert order_status in self.driver.find_element(By.ID, 'content').text
