# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys


class TestDiscountpret():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_discountpret(self):
        # Test name: discount_pret
        # Step # | name | target | value
        # 1 | open | /en/ |
        self.driver.get("http://34.118.122.203/en/")
        # 2 | setWindowSize | 1936x1056 |
        self.driver.set_window_size(1936, 1056)
        # 3 | click | name=s |
        self.driver.find_element(By.NAME, "s").click()
        # 4 | type | name=s | hummin
        self.driver.find_element(By.NAME, "s").send_keys("hummin")
        # 5 | sendKeys | name=s | ${KEY_ENTER}
        self.driver.find_element(By.NAME, "s").send_keys(Keys.ENTER)
        # 6 | click | css=.js-product:nth-child(1) img |
        self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(1) img").click()
        regular_price = self.driver.find_element(By.CLASS_NAME,"regular-price").text
        reduced_price = self.driver.find_element(By.CLASS_NAME,"current-price-value").text
        assert '19.12' in reduced_price
        assert '19.12' not in regular_price


if __name__ == '__main__':
    pytest.main()